# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
t = torch.randn(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
u = torch.randn(1, 7)
# Perform matrix multiplication 
v = t @ u.T
v

tensor([[-1.2885],
        [ 3.0294],
        [-3.9650],
        [ 5.1926],
        [ 1.3993],
        [ 7.2463],
        [ 4.4337]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t = torch.randn(7, 7)
u = torch.randn(1, 7)

# Matrix multiply tensors
v = t @ u.T
v

tensor([[ 3.5168],
        [ 2.1984],
        [-1.7815],
        [ 3.8600],
        [-1.5010],
        [-1.6916],
        [-2.9352]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU

device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU

t_A = torch.randn(2, 3).to(device)
t_B = torch.randn(2, 3).to(device)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
t_C = t_A @ t_B.T
t_C

tensor([[ 0.5595,  0.4036],
        [-0.5087,  0.2792]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
mx = torch.max(t_C)
# Find min
mn = torch.min(t_C)

print(f"max element in t_C: {mx}, min element in t_C: {mn}")

max element in t_C: 0.5594881176948547, min element in t_C: -0.5086871385574341


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
amx = torch.argmax(t_C)
amn = torch.argmin(t_C)
# Find arg min
print(f"argmax in t_C: {amx}, argmin in t_C: {amn}")

argmax in t_C: 0, argmin in t_C: 2



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(0)

# Create random tensor
r = torch.randn(1, 1, 1, 10)

# Remove single dimensions
t = torch.squeeze(r)

# Print out tensors and their shapes
print(r, r.shape)
print(t, t.shape)

tensor([[[[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033,
            0.8380, -0.7193, -0.4033]]]]) torch.Size([1, 1, 1, 10])
tensor([ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845, -1.3986,  0.4033,  0.8380,
        -0.7193, -0.4033]) torch.Size([10])
